name: push-run-test-suite
run-name: ${{ github.event.repository.name }} ${{ github.event.ref }} ${{ github.event.head_commit.message }} run test suite.
on: [push]
jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          tools: composer:v2
      - name : Install php-coveralls
        run: composer global require php-coveralls/php-coveralls:~2.5
      - name: Install dependencies
        run: composer install --dev --no-interaction
      - name: Create build directory
        run: mkdir -p build/logs
      - name: Run test suite
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml test
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php-coveralls --coverage_clover=build/logs/clover.xml -v
  